# Generated by Django 2.2 on 2020-03-28 02:44

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('storage', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ArticlePost',
            new_name='StoragePost',
        ),
    ]
